// <auto-generated />
using MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620084746_AddPhongBan")]
    partial class AddPhongBan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MVC.Models.Entities.PhongBan", b =>
                {
                    b.Property<string>("MaPhongBan")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaPhongBan");

                    b.ToTable("PhongBans");
                });
#pragma warning restore 612, 618
        }
    }
}
